### ISSUE TITLE
wdio cucumber example

### ISSUE THREAD

**Issue by olexandr13** [testomatio/examples#63]
[b9fabf37bb9a/)](https://app.crisp.chat/website/4192ab4e-8b76-4b7e-a8c4-ea66dea249e7/inbox/session_651f48cd-f209-425e-b295-b9fabf37bb9a/)

**Comment by olexandr13** [comment]
other reporters example

**Comment by poliarush** [comment]
linked to https://github.com/testomatio/testomatio/issues/530
linked to https://github.com/testomatio/examples/issues/60

**Comment by olexandr13** [comment]
added
